### ISSUE TITLE
[Suggestion] Add ability to download ems package directly from OpenBaton server

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#70] opened 2017-02-06 09:28 UTC
Currently you are using cloud-init to download and install ems from public repo, when instance is booted. For some closed environments this may not be possible.

Solution for this problem would be an option that would allow users to put their own version of ems package (tar, rpm, deb, ...) on OpenBaton server. Package should be available over http/s protocol, so that instance with modified "user-data" can download it directly from OpenBaton server at boot time.

**Comment by marcellom** [comment] 2018-09-24 08:32
Duplicate of https://github.com/openbaton/generic-vnfm/issues/15

**Closed by marcellom** 2018-09-24 08:32 UTC
Labels: enhancement
