### ISSUE TITLE
Uppercase letters and other chars in VNF names cause NSR fails

### ISSUE THREAD

**Issue by KLuka** [openbaton/NFVO#35] opened 2016-09-21 14:31 UTC
Problem can be reproduced if one uses uppercase letters or underscore in VNF name (maybe even some other characters ?). For example:
- `UPPERCASE-iperf-client-vnfd` 
- `under_score-iperf-client-vnfd`

From generic-vnfm log you can see that uppercase chars are changed to lowercase and underscores are changed to dashes (-). This causes problems for RabbitMQ communication because the names don't match and after a while the NSR goes to ERROR state.

```
2016-09-21 14:03:11.799 DEBUG 2038 --- [SimpleAsyncTaskExecutor-1] o.o.vnfm.generic.utils.EmsRegistrator    : EMSRegister received: {"hostname":"uppercase-iperf-client-vnfd-166"}
2016-09-21 14:03:32.180 DEBUG 2038 --- [SimpleAsyncTaskExecutor-1] o.o.vnfm.generic.utils.EmsRegistrator    : EMSRegister received: {"hostname":"under-score-iperf-client-vnfd-262"}
...
2016-09-21 14:07:03.089 DEBUG 2038 --- [SimpleAsyncTaskExecutor-14] o.o.common.vnfm_sdk.AbstractVnfm         : Waiting for under_score-iperf-client-vnfd-262 ems to be started... (245 secs)
2016-09-21 14:07:03.090 ERROR 2038 --- [SimpleAsyncTaskExecutor-14] o.o.common.vnfm_sdk.AbstractVnfm         : ERROR: 
java.lang.RuntimeException: no ems for hostame: under_score-iperf-client-vnfd-262
...
```

**Comment by lorenzotomasini** [comment] 2016-10-13 09:44
This is fixed in this [commit](https://github.com/openbaton/generic-vnfm/commit/84a1c60ad5a593e6d64977ce375c18ef8d091e2d).

It will be soon included in the master and in the next release

**Comment by KLuka** [comment] 2016-10-13 10:21
Hi, this does solve the issue for uppercase letter, but the problem with dashes still remains. So please keep this issue opened until proper fix is released, to that your users don't hit the same problems.

**Comment by lorenzotomasini** [comment] 2016-10-13 10:44
Yes you are right, we need a regular expression to change the hostname check. we will keep on working on it

**Comment by DasSnehashish** [comment] 2016-12-06 06:27
Hi,
i am also facing same issue .but what i am anylyzing till now that ..not the issue with upper case and lower case ...the issue is EMS project is not running in newly created VM in openstack Env.. 
please check my concern in this ISSUES then you may be understand ..

**Comment by gc4rella** [comment] 2016-12-06 17:43
@radoslavvlaskovski please check that this issue is solved.

**Comment by mpauls** [comment] 2016-12-20 11:27
Fixed by not using the VNF name anymore. Now it uses the numeric identifiers generated when creating the hostname

**Closed by mpauls** 2016-12-20 11:27 UTC
Labels: bug
