### ISSUE TITLE
OpenBaton OpenStack NSR error 

### ISSUE THREAD

**Issue by djamaa** [openbaton/NFVO#291] opened 2018-04-27 00:35 UTC
hello
when I launch the NSD the VNF record state goes from NULL to ERROR, giving this message,
ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-7014051 successfully on VimInstance pop-2. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: 2751059d-abc7-4866-a5a3-2569b63b62b4) is not yet in active. Try again later...
#290

**Comment by ccollicutt** [comment] 2018-04-30 18:09
I experience this same issue.

**Comment by askmanas** [comment] 2018-05-09 11:58
Hi All,

I also landed up facing the same issue. Below is the openbaton.log

2018-05-09 04:55:11.299  INFO 4369 --- [http-nio-8080-exec-10] o.o.n.c.a.NetworkServiceRecordManagement : Looking for NetworkServiceDescriptor with ID: 201a2eee-f4b1-4858-9c36-9de3808ee70e
2018-05-09 04:55:11.470  INFO 4369 --- [http-nio-8080-exec-10] o.o.n.c.a.NetworkServiceRecordManagement : Checking if all vnfm are registered and active
2018-05-09 04:55:11.546  WARN 4369 --- [http-nio-8080-exec-10] o.o.n.c.a.NetworkServiceRecordManagement : Quota check is disabled... Please enable for comprehensive grant operation
2018-05-09 04:55:17.329  INFO 4369 --- [OpenBatonAsyncTask-26] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Executing Task grantoperationTask for vnfr iperf-server. Cyclic=false
2018-05-09 04:55:17.373  INFO 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: GrantOperation on VNFR: iperf-server
2018-05-09 04:55:17.422  INFO 4369 --- [OpenBatonAsyncTask-24] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Executing Task grantoperationTask for vnfr iperf-client. Cyclic=false
2018-05-09 04:55:17.470  INFO 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: GrantOperation on VNFR: iperf-client
2018-05-09 04:55:17.528  WARN 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : Checking quota is disabled, please consider to enable it
2018-05-09 04:55:17.652  INFO 4369 --- [OpenBatonAsyncTask-29] o.o.n.core.core.VnfPlacementManagement   : Chosen VimInstance: Optional[OpenstackVimInstance{tenant='7b98eb7f007f488892d909129c7f4674', username='demo', password='secret', keyPair='openbaton-key', securityGroups=[default], flavours=[DeploymentFlavour{flavour_key='m1.tiny', extId='1', ram=512, disk=1, vcpus=1} BaseEntity{id='e48491a6-9025-40f5-a5e3-c4f4d87e36e9', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.medium', extId='3', ram=4096, disk=40, vcpus=2} BaseEntity{id='ee694f5f-fd55-431a-bea2-8f491c97a60d', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='cirros256', extId='c1', ram=256, disk=0, vcpus=1} BaseEntity{id='99ca1f76-28c8-4b31-a9b5-7775103fd4cd', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.nano', extId='42', ram=64, disk=0, vcpus=1} BaseEntity{id='3bf8f65c-ebc0-4b03-943f-a5183365cb45', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds512M', extId='d1', ram=512, disk=5, vcpus=1} BaseEntity{id='a3461716-380a-465e-aa03-14c7a81c8fe1', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.small', extId='239636af-d8f5-42ea-a658-100934f511c6', ram=2048, disk=20, vcpus=2} BaseEntity{id='aaa5ed89-2a93-4bc8-95cd-c6450ee285a7', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.micro', extId='84', ram=128, disk=0, vcpus=1} BaseEntity{id='b1b7442f-22e8-44b9-9098-1cbea46a4e58', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds1G', extId='d2', ram=1024, disk=10, vcpus=1} BaseEntity{id='0918162d-4c15-4f55-aca9-820b6cf8a793', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds2G', extId='d3', ram=2048, disk=10, vcpus=2} BaseEntity{id='745ae1ba-7ef3-4d7f-aba1-131f17279232', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.xlarge', extId='5', ram=16384, disk=160, vcpus=8} BaseEntity{id='04d3d8f5-0284-4630-a910-1d697f507192', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds4G', extId='d4', ram=4096, disk=20, vcpus=4} BaseEntity{id='37630a08-b4f8-43d4-a233-ec5128b5c52d', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.large', extId='4', ram=8192, disk=80, vcpus=4} BaseEntity{id='b0cc4da5-66a3-4463-b116-ea7483360d68', version=0, projectId='null', shared=false, metadata={}}], images=[NFVImage{extId='b9fb8d08-c00c-45f5-9dfb-c0ec9d46e0f5', name='ubuntu-trusty', minRam=2048, minDiskSpace=20, minCPU='null', isPublic=true, diskFormat='QCOW2', containerFormat='BARE', created=2018-05-09 00:19:19.0, updated=2018-05-09 00:19:22.0, status=ACTIVE} BaseNfvImage{extId='b9fb8d08-c00c-45f5-9dfb-c0ec9d46e0f5', created=2018-05-09 00:19:19.0} BaseEntity{id='e5875b08-3fa7-4e97-9217-d60927ed7cca', version=0, projectId='null', shared=false, metadata={}}, NFVImage{extId='cda6cae3-2a4a-4738-8ca8-af482ef731c1', name='cirros', minRam=0, minDiskSpace=0, minCPU='null', isPublic=true, diskFormat='QCOW2', containerFormat='BARE', created=2018-05-08 05:30:59.0, updated=2018-05-09 04:29:43.0, status=ACTIVE} BaseNfvImage{extId='cda6cae3-2a4a-4738-8ca8-af482ef731c1', created=2018-05-08 05:30:59.0} BaseEntity{id='8e7e1765-a391-4097-8683-3b7a706e93a9', version=0, projectId='null', shared=false, metadata={}}], networks=[Network{external=false, extShared=false, subnets=[Subnet{name='private-subnet', extId='9a576d37-f9d4-4b34-bc3b-cb1f9bbaa234', networkId='f0df92da-cf81-4325-810d-d7afb98045c4', cidr='10.0.0.0/26', gatewayIp='10.0.0.1'} BaseEntity{id='0599e106-26ee-4058-8c73-fdc28ebf1d68', version=0, projectId='null', shared=false, metadata={}}, Subnet{name='ipv6-private-subnet', extId='a4649e1b-6db3-468b-80f9-b5950d145571', networkId='f0df92da-cf81-4325-810d-d7afb98045c4', cidr='fd0c:5f49:10a5::/64', gatewayIp='fd0c:5f49:10a5::1'} BaseEntity{id='a9c38895-cb5c-4348-bf55-6f71bdaea0d7', version=0, projectId='null', shared=false, metadata={}}]} BaseNetwork{name='private', extId='f0df92da-cf81-4325-810d-d7afb98045c4'} BaseEntity{id='af96ba55-c0e4-4427-8c67-76e27697d00c', version=1, projectId='null', shared=false, metadata={}}, Network{external=true, extShared=false, subnets=[]} BaseNetwork{name='public', extId='fc957f56-55cc-4dfd-95aa-8284b3600594'} BaseEntity{id='24dc8f3b-ae04-45ad-beba-6678f2fd02f2', version=1, projectId='null', shared=false, metadata={}}]} BaseVimInstance{name='devstack-demo', location=Location{name='Pune', latitude='52.525876', longitude='13.314400'} BaseEntity{id='0c5c6d1a-c1fc-4e59-8916-b5970d375d95', version=0, projectId='null', shared=false, metadata={}}, type='openstack', active=true} BaseEntity{id='3f7b5a16-0ac8-498b-855a-972149842da1', version=1, projectId='bf3d916c-a61f-40f7-a426-df3e7e607fee', shared=false, metadata={}}]
2018-05-09 04:55:17.716  WARN 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : Checking quota is disabled, please consider to enable it
2018-05-09 04:55:17.742  INFO 4369 --- [OpenBatonAsyncTask-30] o.o.n.core.core.VnfPlacementManagement   : Chosen VimInstance: Optional[OpenstackVimInstance{tenant='7b98eb7f007f488892d909129c7f4674', username='demo', password='secret', keyPair='openbaton-key', securityGroups=[default], flavours=[DeploymentFlavour{flavour_key='ds1G', extId='d2', ram=1024, disk=10, vcpus=1} BaseEntity{id='0918162d-4c15-4f55-aca9-820b6cf8a793', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds2G', extId='d3', ram=2048, disk=10, vcpus=2} BaseEntity{id='745ae1ba-7ef3-4d7f-aba1-131f17279232', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.tiny', extId='1', ram=512, disk=1, vcpus=1} BaseEntity{id='e48491a6-9025-40f5-a5e3-c4f4d87e36e9', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='cirros256', extId='c1', ram=256, disk=0, vcpus=1} BaseEntity{id='99ca1f76-28c8-4b31-a9b5-7775103fd4cd', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.medium', extId='3', ram=4096, disk=40, vcpus=2} BaseEntity{id='ee694f5f-fd55-431a-bea2-8f491c97a60d', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.nano', extId='42', ram=64, disk=0, vcpus=1} BaseEntity{id='3bf8f65c-ebc0-4b03-943f-a5183365cb45', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.small', extId='239636af-d8f5-42ea-a658-100934f511c6', ram=2048, disk=20, vcpus=2} BaseEntity{id='aaa5ed89-2a93-4bc8-95cd-c6450ee285a7', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.micro', extId='84', ram=128, disk=0, vcpus=1} BaseEntity{id='b1b7442f-22e8-44b9-9098-1cbea46a4e58', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.xlarge', extId='5', ram=16384, disk=160, vcpus=8} BaseEntity{id='04d3d8f5-0284-4630-a910-1d697f507192', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds512M', extId='d1', ram=512, disk=5, vcpus=1} BaseEntity{id='a3461716-380a-465e-aa03-14c7a81c8fe1', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='m1.large', extId='4', ram=8192, disk=80, vcpus=4} BaseEntity{id='b0cc4da5-66a3-4463-b116-ea7483360d68', version=0, projectId='null', shared=false, metadata={}}, DeploymentFlavour{flavour_key='ds4G', extId='d4', ram=4096, disk=20, vcpus=4} BaseEntity{id='37630a08-b4f8-43d4-a233-ec5128b5c52d', version=0, projectId='null', shared=false, metadata={}}], images=[NFVImage{extId='cda6cae3-2a4a-4738-8ca8-af482ef731c1', name='cirros', minRam=0, minDiskSpace=0, minCPU='null', isPublic=true, diskFormat='QCOW2', containerFormat='BARE', created=2018-05-08 05:30:59.0, updated=2018-05-09 04:29:43.0, status=ACTIVE} BaseNfvImage{extId='cda6cae3-2a4a-4738-8ca8-af482ef731c1', created=2018-05-08 05:30:59.0} BaseEntity{id='8e7e1765-a391-4097-8683-3b7a706e93a9', version=0, projectId='null', shared=false, metadata={}}, NFVImage{extId='b9fb8d08-c00c-45f5-9dfb-c0ec9d46e0f5', name='ubuntu-trusty', minRam=2048, minDiskSpace=20, minCPU='null', isPublic=true, diskFormat='QCOW2', containerFormat='BARE', created=2018-05-09 00:19:19.0, updated=2018-05-09 00:19:22.0, status=ACTIVE} BaseNfvImage{extId='b9fb8d08-c00c-45f5-9dfb-c0ec9d46e0f5', created=2018-05-09 00:19:19.0} BaseEntity{id='e5875b08-3fa7-4e97-9217-d60927ed7cca', version=0, projectId='null', shared=false, metadata={}}], networks=[Network{external=false, extShared=false, subnets=[Subnet{name='ipv6-private-subnet', extId='a4649e1b-6db3-468b-80f9-b5950d145571', networkId='f0df92da-cf81-4325-810d-d7afb98045c4', cidr='fd0c:5f49:10a5::/64', gatewayIp='fd0c:5f49:10a5::1'} BaseEntity{id='a9c38895-cb5c-4348-bf55-6f71bdaea0d7', version=0, projectId='null', shared=false, metadata={}}, Subnet{name='private-subnet', extId='9a576d37-f9d4-4b34-bc3b-cb1f9bbaa234', networkId='f0df92da-cf81-4325-810d-d7afb98045c4', cidr='10.0.0.0/26', gatewayIp='10.0.0.1'} BaseEntity{id='0599e106-26ee-4058-8c73-fdc28ebf1d68', version=0, projectId='null', shared=false, metadata={}}]} BaseNetwork{name='private', extId='f0df92da-cf81-4325-810d-d7afb98045c4'} BaseEntity{id='af96ba55-c0e4-4427-8c67-76e27697d00c', version=1, projectId='null', shared=false, metadata={}}, Network{external=true, extShared=false, subnets=[]} BaseNetwork{name='public', extId='fc957f56-55cc-4dfd-95aa-8284b3600594'} BaseEntity{id='24dc8f3b-ae04-45ad-beba-6678f2fd02f2', version=1, projectId='null', shared=false, metadata={}}]} BaseVimInstance{name='devstack-demo', location=Location{name='Pune', latitude='52.525876', longitude='13.314400'} BaseEntity{id='0c5c6d1a-c1fc-4e59-8916-b5970d375d95', version=0, projectId='null', shared=false, metadata={}}, type='openstack', active=true} BaseEntity{id='3f7b5a16-0ac8-498b-855a-972149842da1', version=1, projectId='bf3d916c-a61f-40f7-a426-df3e7e607fee', shared=false, metadata={}}]
2018-05-09 04:55:18.322  INFO 4369 --- [OpenBatonAsyncTask-30] o.openbaton.nfvo.core.api.VimManagement  : Refreshing vim
2018-05-09 04:55:22.969  INFO 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : Choose all Vim Instance for vnfr: iperf-server
2018-05-09 04:55:24.339  INFO 4369 --- [OpenBatonAsyncTask-30] o.openbaton.nfvo.core.api.VimManagement  : Refreshing vim
2018-05-09 04:55:24.874  INFO 4369 --- [OpenBatonAsyncTask-26] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Executing Task allocateresourcesTask for vnfr iperf-server. Cyclic=false
2018-05-09 04:55:24.875  INFO 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: AllocateResources for VNFR: iperf-server
2018-05-09 04:55:25.040  INFO 4369 --- [OpenBatonAsyncTask-23] o.o.nfvo.core.core.ResourceManagement    : Checking if Flavor m1.small exists...
2018-05-09 04:55:25.102  INFO 4369 --- [OpenBatonAsyncTask-23] o.o.nfvo.core.core.ResourceManagement    : FloatingIp chosen are: {private=random}
2018-05-09 04:55:25.103  INFO 4369 --- [OpenBatonAsyncTask-23] org.openbaton.vim_impl.vim.GenericVIM    : Found DeploymentFlavour with ExtId: 239636af-d8f5-42ea-a658-100934f511c6 of DeploymentFlavour with name: m1.small on VimInstance devstack-demo
2018-05-09 04:55:26.152 ERROR 4369 --- [OpenBatonAsyncTask-23] org.openbaton.plugin.utils.PluginCaller  : Got Vim Driver Exception with cause: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:26.155 ERROR 4369 --- [OpenBatonAsyncTask-23] org.openbaton.plugin.utils.PluginCaller  : Got Vim Driver Exception with server: null
2018-05-09 04:55:26.196 ERROR 4369 --- [OpenBatonAsyncTask-23] org.openbaton.vim_impl.vim.GenericVIM    : Not launched VM with hostname iperf-server-9991879 successfully on VimInstance devstack-demo. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:26.226  WARN 4369 --- [OpenBatonAsyncTask-23] org.openbaton.vim_impl.vim.GenericVIM    : Exception thrown while deploying... Try to recover 'iperf-server-9991879' from VIM directly
2018-05-09 04:55:26.651  INFO 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : Choose all Vim Instance for vnfr: iperf-client
2018-05-09 04:55:27.904 ERROR 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-9991879 successfully on VimInstance devstack-demo. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:27.905  INFO 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : The VM was not correctly deployed. ExtId is: unknown
2018-05-09 04:55:28.110  INFO 4369 --- [OpenBatonAsyncTask-23] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Executing Task allocateresourcesTask for vnfr iperf-client. Cyclic=false
2018-05-09 04:55:28.111  INFO 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : Executing task: AllocateResources for VNFR: iperf-client
2018-05-09 04:55:28.181  INFO 4369 --- [OpenBatonAsyncTask-24] o.o.nfvo.core.core.ResourceManagement    : Checking if Flavor m1.small exists...
2018-05-09 04:55:28.264  INFO 4369 --- [OpenBatonAsyncTask-24] o.o.nfvo.core.core.ResourceManagement    : FloatingIp chosen are: {private=random}
2018-05-09 04:55:28.265  INFO 4369 --- [OpenBatonAsyncTask-24] org.openbaton.vim_impl.vim.GenericVIM    : Found DeploymentFlavour with ExtId: 239636af-d8f5-42ea-a658-100934f511c6 of DeploymentFlavour with name: m1.small on VimInstance devstack-demo
2018-05-09 04:55:29.143  INFO 4369 --- [OpenBatonAsyncTask-25] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Executing Task errorTask for vnfr iperf-server. Cyclic=false
2018-05-09 04:55:29.143  INFO 4369 --- [OpenBatonAsyncTask-25] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Sent INSTANTIATE to VNF: iperf-server
2018-05-09 04:55:29.144 ERROR 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : ERROR from VNFM: org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-9991879 successfully on VimInstance devstack-demo. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:29.165 ERROR 4369 --- [OpenBatonAsyncTask-29] o.o.n.v.tasks.abstracts.AbstractTask     : Received ERROR message from VNFM related to VNFR: iperf-server
2018-05-09 04:55:29.640 ERROR 4369 --- [OpenBatonAsyncTask-24] org.openbaton.plugin.utils.PluginCaller  : Got Vim Driver Exception with cause: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:29.640 ERROR 4369 --- [OpenBatonAsyncTask-24] org.openbaton.plugin.utils.PluginCaller  : Got Vim Driver Exception with server: null
2018-05-09 04:55:29.660 ERROR 4369 --- [OpenBatonAsyncTask-24] org.openbaton.vim_impl.vim.GenericVIM    : Not launched VM with hostname iperf-client-944251 successfully on VimInstance devstack-demo. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:29.661  WARN 4369 --- [OpenBatonAsyncTask-24] org.openbaton.vim_impl.vim.GenericVIM    : Exception thrown while deploying... Try to recover 'iperf-client-944251' from VIM directly
2018-05-09 04:55:30.604 ERROR 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-client-944251 successfully on VimInstance devstack-demo. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:30.606  INFO 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : The VM was not correctly deployed. ExtId is: unknown
2018-05-09 04:55:31.033  INFO 4369 --- [OpenBatonAsyncTask-27] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Executing Task errorTask for vnfr iperf-client. Cyclic=false
2018-05-09 04:55:31.034  INFO 4369 --- [OpenBatonAsyncTask-27] o.o.nfvo.vnfm_reg.state.VnfStateHandler  : Sent INSTANTIATE to VNF: iperf-client
2018-05-09 04:55:31.034 ERROR 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : ERROR from VNFM: org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-client-944251 successfully on VimInstance devstack-demo. Caused by: org.openbaton.exceptions.VimDriverException: Image (name: cda6cae3-2a4a-4738-8ca8-af482ef731c1) is not yet in active. Try again later...
2018-05-09 04:55:31.057 ERROR 4369 --- [OpenBatonAsyncTask-30] o.o.n.v.tasks.abstracts.AbstractTask     : Received ERROR message from VNFM related to VNFR: iperf-client

**Comment by mpauls** [comment] 2018-05-09 12:27
This issue is fixed now in the master branch of the openstack4j-plugin.

It is a problem of the openstack4j libraries we are using.

For the moment we made this additional check configurable where by default it is disabled. Once this issue is fixed in the libraries, we will enable it again by default.

**Closed** 2018-05-09 12:27 UTC
